# netlify.toml (versión optimizada para el Next.js Runtime de Netlify)

[build]
  # El comando de build es correcto. Netlify lo ejecutará.
  command = "npx next build"

  # ¡CAMBIO CLAVE! 
  # Apuntamos al directorio de salida estándar de Next.js (.next) en lugar de "out".
  # Esto permite a Netlify usar su runtime especializado para Next.js.
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Los encabezados de seguridad que tenías están perfectos. Los mantenemos.
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[functions]
  directory = "netlify/functions"

# La redirección para SPAs ha sido eliminada, ya que no es necesaria
# con el Next.js Runtime de Netlify.